---
- name: Webサイトをデプロイ
  hosts: all
  become: true
  vars:
    use_local_logo: false
    site_message: Hello World!
    html_dir: '{% if ansible_os_family == "RedHat" %}/usr/share/nginx/html{% else %}/var/www/html{% endif %}'
  tasks:
    - name: nginxとfiewalldをインストール
      package:  # 汎用Linuxパッケージ管理モジュール(yum ,apt...)
        name:
          - nginx
          - firewalld
        state: present

    - name: nginxとfirewalldのサービス起動/有効化
      service:
        name: nginx
        state: started
        enabled: true
      loop:
        - nginx
        - firewalld

    - name: firewalldサービス起動/有効化
      service:
        name: firewalld
        state: started
        enabled: true

    - name: firewalldでhttpアクセスを許可
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: ローカルロゴイメージをコピー
      copy:
        src: files/logo.png
        dest: '{{ html_dir }}/logo.png'
      when: use_local_logo | bool is true

    - name: index.htmlを展開
      template:
        src: templates/index.html.j2
        dest: '{{ html_dir }}/index.html'
